pipeline {
    agent {
        docker {
            image 'maven:3-alpine'
            args '-e "http_proxy=http://10.60.135.36:8800" -e "https_proxy=http://10.60.135.36:8800"'
        }
    }
    stages {
        stage('Build') {
            steps {
                sh 'mvn -B -DskipTests clean package'
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deliver') {
            steps {
                sh './jenkins/scripts/deliver.sh'
            }
        }
    }
}
